name: Release
on: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Setup Node Version
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install all dependencies
      run: npm install
    - name: Package Extension
      run: npm run build